spring:
  datasource:
    url:  jdbc:mysql://10.175.94.58:6666/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.junior.file_system.entity

filepath: "E:\\file_system\\"
server:
  address: 0.0.0.0
logging:
  pattern:
    console: "%d - %msg%n"
  file:
    name: file_system.log
